# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install denpendencies
    before: sudo apt-get update -y && sudo apt-get install -y libosmesa6-dev
    init: curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh" && bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge && echo 'export PATH="$HOME/mambaforge/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc && mamba init && source $HOME/.bashrc
    command: mamba create -n vmtk python==3.6.9 -y && mamba activate vmtk && mamba install -y -c vmtk vtk itk vmtk && pip install itk scikit-image nibabel xlwt xlrd xlutils vtk tqdm && python fixbug_vmtk.py && echo "......................................" && echo "All denpendencies are installed successfully!!"
    

  # - name: try demo tasks.
  #   init: mamba activate vmtk
  #   command: python extract_feature.py
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
